### ISSUE TITLE
Rank Quoter: API queries concerning percentile and rank

### ISSUE THREAD

**Issue by DanielKrawisz** [MatterPool/boostpow-api#5]
Provide information about boosted content by percentile over a given time. Since we do not have much boost business now, we need to account for cases in which no content was boosted or one. We also want to account for times when we have lots of business. 
### percentile by difficulty
request: 
* difficulty
* time range
* (optional) category or all boosted content if not given. 
response: percentile of content boosted by less than that difficulty in the given time for the given category. There can be more than one boost per content. We look at content by total amount boosted, not by individual boosts. 
### difficulty by percentile
request: 
* percentile
* time range
* (optional) category or all boosted content if not given. 
response: difficulty nearest the given percentile and its percentile for the given category. (there may not be a data for exactly the percentile given)
### rank by difficulty
request: 
* difficulty
* time range
* (optional) category or all boosted content if not given. 
response: highest rank below the given difficulty for the given category. 
### difficulty by rank
request: 
* rank
* time range
* (optional) category or all boosted content if not given. 
response: boosted difficulty of the content with the given rank. 
### max boost
request: 
* time range
* (optional) category
Response: max total difficulty by which some content was boosted in the time range. (this is really the same as difficulty by rank for rank = 0)
### series of percentiles by time
this is needed to construct the web form. we need a series of percentiles that can be used to extrapolate a function
request: 
* time range
* (optional) category
response: 
* a response indicating no data or
* a max value (which isn't technically a percentile) and a list of percentiles in order starting at zero (the min value). The size of the list should be chosen based on the amount of data. In the limit of lots of data, return percentiles at 1%, 2%, 4%, 6%, 8%, 10%, 20%, 40%, 60%, 80%, 90%, 92%, 94%, 96%, 98%, 99%. The top and bottom percentiles may be further subdivided in a similar way.

**Comment by attilaaf** [comment]
superseded by https://github.com/MatterPool/boostpow-publish/issues/12
