### ISSUE TITLE
API query for expected time to complete a boost job.

### ISSUE THREAD

**Issue by DanielKrawisz** [MatterPool/boostpow-api#6]
request: a difficulty and price in satoshis. 
response: error or estimated time to complete, which is a positive number or infinity.

There is one call but the internal logic is different for boost contract vs boost bounty. 

If job is unknown, error.

If job is complete, expected time is zero. 

For bounty, compare profitability of boost output to profitability of network. If profitability is negative, expected time is infinite. If positive, look at total network hashpower and assume hashpower assigned to job is in proportion to profitability. See comment below.

For contract job that is not ours, time is unknown. 

For contract job that is ours, look at its place in the queue, total difficulty of all jobs up to that place, and hashpower assigned to contract jobs.

**Comment by DanielKrawisz** [comment]
How to estimate Boost Bounty job times in detail:

The way this is done is to compare profitability for the bounty script compared to the whole network. If the script profitability is negative, estimated time is infinite. Otherwise, it is 

network_hashpower script_difficulty script_profitability / network_profitability 

Profitability is 

(income - cost) / cost

cost is the price per difficulty times total difficulty. Price per difficulty in a function that Attila has to implement.

**Comment by attilaaf** [comment]
What we expect is:

`GET api.matterpool.io/api/v1/boost/boostfeequote`
